language: c
sudo: required
install: wget https://raw.githubusercontent.com/ocaml/ocaml-ci-scripts/master/.travis-opam.sh
script: bash -ex .travis-opam.sh
env:
  global:
  matrix:
  - OCAML_VERSION=4.03 PACKAGE=mirage-net-macosx
  - OCAML_VERSION=4.04 PACKAGE=mirage-net-macosx
os:
  - osx
